window.PRODUCTS = [
  {
    "id": 1,
    "name": "La Nuit Trésor",
    "brand": "Lancôme",
    "inspired": "La Nuit Trésor — Lancôme",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/la-nuit-trsor.webp",
    "official": "https://www.lancome.com.br/la-nuit-tresor",
    "notes": [
      "Pera",
      "Rosa negra",
      "Pralinê",
      "Baunilha"
    ],
    "short": "Gourmand floral, intenso e sedutor.",
    "description": "Uma fragrância noturna e envolvente, em que frutas maduras e rosa escura encontram um acorde gourmand de pralinê, baunilha e madeiras profundas.",
    "occasion": "Noites e ocasiões especiais",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 2,
    "name": "Musk White Intense",
    "brand": "Lattafa",
    "inspired": "Musk White Intense — Lattafa",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/musk-white-intense.webp",
    "official": "https://www.lattafa-usa.com/",
    "notes": [
      "Almíscar branco",
      "Flores claras",
      "Âmbar",
      "Baunilha"
    ],
    "short": "Almiscarado, limpo e confortável.",
    "description": "Um perfume macio e elegante, construído ao redor de almíscares brancos, flores delicadas e uma base levemente adocicada e ambarada.",
    "occasion": "Dia a dia e trabalho",
    "season": "Todas as estações",
    "performance": "Moderada"
  },
  {
    "id": 3,
    "name": "Paradoxe",
    "brand": "Prada",
    "inspired": "Paradoxe — Prada",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/paradoxe.webp",
    "official": "https://www.prada-beauty.com/fragrance/paradoxe/",
    "notes": [
      "Néroli",
      "Jasmim",
      "Âmbar",
      "Almíscar"
    ],
    "short": "Floral ambarado, moderno e luminoso.",
    "description": "Combina flores brancas radiantes com uma base quente e confortável, criando uma assinatura feminina contemporânea, elegante e muito versátil.",
    "occasion": "Trabalho, encontros e eventos",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 4,
    "name": "Delina Exclusif",
    "brand": "Parfums de Marly",
    "inspired": "Delina Exclusif — Parfums de Marly",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/delina-exclusif.webp",
    "official": "https://parfums-de-marly.com/products/delina-exclusif",
    "notes": [
      "Lichia",
      "Rosa",
      "Incenso",
      "Baunilha"
    ],
    "short": "Rosa cremosa, doce e opulenta.",
    "description": "Uma rosa luxuosa envolvida por frutas, baunilha, incenso e madeiras macias. Feminina, intensa e sofisticada.",
    "occasion": "Encontros e eventos especiais",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 5,
    "name": "Rose Oud",
    "brand": "Jo Malone London",
    "inspired": "Rose Oud — Jo Malone London",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/rose-oud.webp",
    "official": "https://www.jomalone.com/",
    "notes": [
      "Rosa",
      "Oud",
      "Pralinê",
      "Âmbar"
    ],
    "short": "Floral amadeirado, quente e refinado.",
    "description": "Rosa aveludada e oud escuro se encontram em uma composição rica, elegante e envolvente, com doçura discreta e presença marcante.",
    "occasion": "Noites e ocasiões formais",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 6,
    "name": "Oriana",
    "brand": "Parfums de Marly",
    "inspired": "Oriana — Parfums de Marly",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/oriana.webp",
    "official": "https://parfums-de-marly.com/products/oriana",
    "notes": [
      "Mandarina",
      "Flor de laranjeira",
      "Marshmallow",
      "Almíscar"
    ],
    "short": "Frutado floral, cremoso e delicado.",
    "description": "Uma abertura frutada e cintilante evolui para flores brancas, marshmallow e almíscar, criando uma fragrância alegre, feminina e sofisticada.",
    "occasion": "Encontros e ocasiões especiais",
    "season": "Primavera e outono",
    "performance": "Alta"
  },
  {
    "id": 7,
    "name": "Imagination",
    "brand": "Louis Vuitton",
    "inspired": "Imagination — Louis Vuitton",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/imagination.webp",
    "official": "https://br.louisvuitton.com/por-br/produtos/imagination-nvprod2970067v/LP0219",
    "notes": [
      "Cidra",
      "Bergamota",
      "Chá preto",
      "Ambrox"
    ],
    "short": "Cítrico, elegante e contemporâneo.",
    "description": "Uma fragrância luminosa e sofisticada, com cítricos refinados, especiarias frescas e um elegante acorde de chá preto sobre fundo ambarado.",
    "occasion": "Trabalho, viagens e eventos",
    "season": "Primavera e verão",
    "performance": "Alta"
  },
  {
    "id": 8,
    "name": "La Bomba",
    "brand": "Carolina Herrera",
    "inspired": "La Bomba — Carolina Herrera",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/la-bomba.webp",
    "official": "https://www.carolinaherrera.com/",
    "notes": [
      "Pitaya",
      "Peônia",
      "Frangipani",
      "Baunilha"
    ],
    "short": "Floral frutado, vibrante e exuberante.",
    "description": "Uma criação colorida e expansiva, com frutas tropicais luminosas, flores cremosas e uma base sensual e confortável.",
    "occasion": "Festas, encontros e eventos",
    "season": "Primavera e verão",
    "performance": "Alta"
  },
  {
    "id": 9,
    "name": "La Vie Est Belle",
    "brand": "Lancôme",
    "inspired": "La Vie Est Belle — Lancôme",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/la-vie-est-belle.webp",
    "official": "https://www.lancome.com.br/la-vie-est-belle",
    "notes": [
      "Íris",
      "Pera",
      "Pralinê",
      "Patchouli"
    ],
    "short": "Gourmand, alegre e confortável.",
    "description": "Íris elegante, frutas e um acorde gourmand de pralinê e baunilha formam uma fragrância acolhedora, marcante e muito feminina.",
    "occasion": "Dia a dia, encontros e festas",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 10,
    "name": "Erba Pura",
    "brand": "Xerjoff",
    "inspired": "Erba Pura — Xerjoff",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/erba-pura.webp",
    "official": "https://www.xerjoff.com/products/erba-pura-eau-de-parfum",
    "notes": [
      "Laranja",
      "Frutas mediterrâneas",
      "Baunilha",
      "Almíscar"
    ],
    "short": "Frutado, doce e expansivo.",
    "description": "Uma cesta vibrante de frutas mediterrâneas e cítricos luminosos repousa sobre almíscar macio e baunilha sensual.",
    "occasion": "Festas e ocasiões marcantes",
    "season": "Primavera e verão",
    "performance": "Muito alta"
  },
  {
    "id": 11,
    "name": "J'adore",
    "brand": "Dior",
    "inspired": "J'adore — Dior",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/j-adore.webp",
    "official": "https://www.dior.com/pt_br/beauty/products/jadore-eau-de-parfum",
    "notes": [
      "Ylang-ylang",
      "Jasmim",
      "Rosa",
      "Frutas"
    ],
    "short": "Floral luminoso, elegante e clássico.",
    "description": "Um buquê floral sofisticado e radiante, com flores nobres, frutas delicadas e acabamento macio, feminino e atemporal.",
    "occasion": "Trabalho, eventos e ocasiões formais",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 12,
    "name": "Delina La Rosée",
    "brand": "Parfums de Marly",
    "inspired": "Delina La Rosée — Parfums de Marly",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/delina-la-rose.webp",
    "official": "https://parfums-de-marly.com/products/delina-la-rosee",
    "notes": [
      "Lichia",
      "Pera",
      "Rosa",
      "Almíscar"
    ],
    "short": "Floral aquático, delicado e luminoso.",
    "description": "Uma versão mais fresca e transparente da rosa, com frutas aquosas, peônia e almíscar, ideal para quem busca elegância leve.",
    "occasion": "Dia a dia e encontros",
    "season": "Primavera e verão",
    "performance": "Moderada-alta"
  },
  {
    "id": 13,
    "name": "My Way",
    "brand": "Giorgio Armani",
    "inspired": "My Way — Giorgio Armani",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/my-way.webp",
    "official": "https://www.giorgioarmanibeauty-usa.com/fragrances/womens-perfume/my-way/",
    "notes": [
      "Flor de laranjeira",
      "Tuberosa",
      "Jasmim",
      "Baunilha"
    ],
    "short": "Floral branco, luminoso e moderno.",
    "description": "Flores brancas cremosas ganham brilho cítrico e uma base confortável de baunilha e madeiras claras.",
    "occasion": "Trabalho, encontros e eventos",
    "season": "Primavera e outono",
    "performance": "Alta"
  },
  {
    "id": 14,
    "name": "Lost Cherry",
    "brand": "Tom Ford",
    "inspired": "Lost Cherry — Tom Ford",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/lost-cherry.webp",
    "official": "https://www.tomfordbeauty.com/product/lost-cherry-eau-de-parfum",
    "notes": [
      "Cereja",
      "Amêndoa amarga",
      "Rosa",
      "Fava tonka"
    ],
    "short": "Frutado licoroso, doce e sedutor.",
    "description": "Cereja madura e licorosa encontra amêndoa, flores e uma base quente de baunilha e fava tonka, criando uma assinatura ousada.",
    "occasion": "Noites, encontros e festas",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 15,
    "name": "Coco Mademoiselle",
    "brand": "Chanel",
    "inspired": "Coco Mademoiselle — Chanel",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/coco-mademoiselle.webp",
    "official": "https://www.chanel.com/br/perfumes/p/116520/coco-mademoiselle-eau-de-parfum-spray/",
    "notes": [
      "Laranja",
      "Rosa",
      "Jasmim",
      "Patchouli"
    ],
    "short": "Cítrico floral, chique e versátil.",
    "description": "Cítricos luminosos se unem a rosa, jasmim e patchouli em uma composição elegante, limpa e reconhecidamente sofisticada.",
    "occasion": "Trabalho, eventos e encontros",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 16,
    "name": "L'Eau d'Issey",
    "brand": "Issey Miyake",
    "inspired": "L'Eau d'Issey — Issey Miyake",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/l-eau-d-issey.webp",
    "official": "https://www.isseymiyakeparfums.com/",
    "notes": [
      "Lótus",
      "Rosa",
      "Melão",
      "Madeiras"
    ],
    "short": "Aquático floral, leve e atemporal.",
    "description": "Uma fragrância transparente e delicada, com flores aquáticas, frutas frescas e madeiras claras, perfeita para sensação de limpeza.",
    "occasion": "Dia a dia e trabalho",
    "season": "Primavera e verão",
    "performance": "Moderada"
  },
  {
    "id": 17,
    "name": "Aventus",
    "brand": "Creed",
    "inspired": "Aventus — Creed",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/aventus.webp",
    "official": "https://creedboutique.com/products/aventus",
    "notes": [
      "Abacaxi",
      "Bergamota",
      "Bétula",
      "Almíscar"
    ],
    "short": "Frutado, amadeirado e confiante.",
    "description": "Marcante e versátil, combina uma abertura frutada vibrante com madeiras elegantes e um fundo levemente esfumaçado.",
    "occasion": "Trabalho, encontros e eventos",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 18,
    "name": "Thé Noir 29",
    "brand": "Le Labo",
    "inspired": "Thé Noir 29 — Le Labo",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/th-noir-29.webp",
    "official": "https://www.lelabofragrances.com/the-noir-29-148.html",
    "notes": [
      "Bergamota",
      "Figo",
      "Chá preto",
      "Tabaco"
    ],
    "short": "Aromático, amadeirado e contemplativo.",
    "description": "Figo, folhas secas e chá preto formam uma fragrância elegante e introspectiva, com nuances de tabaco, feno e madeiras.",
    "occasion": "Trabalho criativo e noites",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 19,
    "name": "Acqua di Giò",
    "brand": "Giorgio Armani",
    "inspired": "Acqua di Giò — Giorgio Armani",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/acqua-di-gi.webp",
    "official": "https://www.giorgioarmanibeauty-usa.com/fragrances/mens-cologne/acqua-di-gio/",
    "notes": [
      "Notas marinhas",
      "Bergamota",
      "Jasmim",
      "Cedro"
    ],
    "short": "Aquático, cítrico e clássico.",
    "description": "Uma combinação fresca de notas marinhas, cítricos, ervas aromáticas e madeiras, com sensação limpa e naturalmente elegante.",
    "occasion": "Dia a dia, trabalho e lazer",
    "season": "Primavera e verão",
    "performance": "Moderada-alta"
  },
  {
    "id": 20,
    "name": "Hacivat",
    "brand": "Nishane",
    "inspired": "Hacivat — Nishane",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/hacivat.webp",
    "official": "https://nishane.com/product/hacivat/",
    "notes": [
      "Abacaxi",
      "Toranja",
      "Cedro",
      "Musgo"
    ],
    "short": "Verde, frutado e sofisticado.",
    "description": "Cítricos e abacaxi encontram madeiras e musgo em uma composição elegante, expansiva e de presença marcante.",
    "occasion": "Trabalho, eventos e ocasiões formais",
    "season": "Todas as estações",
    "performance": "Muito alta"
  },
  {
    "id": 21,
    "name": "Allure Homme Sport",
    "brand": "Chanel",
    "inspired": "Allure Homme Sport — Chanel",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/allure-homme-sport.webp",
    "official": "https://www.chanel.com/br/perfumes/p/123630/allure-homme-sport-eau-de-toilette-spray/",
    "notes": [
      "Mandarina",
      "Notas marinhas",
      "Pimenta",
      "Fava tonka"
    ],
    "short": "Fresco, esportivo e elegante.",
    "description": "Mistura cítricos, frescor marinho, especiarias e uma base cremosa, criando um perfume extremamente versátil e refinado.",
    "occasion": "Dia a dia, academia e encontros",
    "season": "Primavera e verão",
    "performance": "Alta"
  },
  {
    "id": 22,
    "name": "L'Eau d'Issey Pour Homme",
    "brand": "Issey Miyake",
    "inspired": "L'Eau d'Issey Pour Homme — Issey Miyake",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/l-eau-d-issey-pour-homme.webp",
    "official": "https://www.isseymiyakeparfums.com/",
    "notes": [
      "Yuzu",
      "Especiarias",
      "Lótus",
      "Vetiver"
    ],
    "short": "Cítrico aquático, limpo e distinto.",
    "description": "Yuzu vibrante, especiarias e madeiras criam um frescor seco e elegante, com personalidade japonesa minimalista.",
    "occasion": "Trabalho e dia a dia",
    "season": "Primavera e verão",
    "performance": "Moderada-alta"
  },
  {
    "id": 23,
    "name": "Bleu de Chanel",
    "brand": "Chanel",
    "inspired": "Bleu de Chanel — Chanel",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/bleu-de-chanel.webp",
    "official": "https://www.chanel.com/br/perfumes/p/107360/bleu-de-chanel-eau-de-parfum-spray/",
    "notes": [
      "Toranja",
      "Incenso",
      "Cedro",
      "Sândalo"
    ],
    "short": "Amadeirado aromático, elegante e versátil.",
    "description": "Cítricos frescos, incenso e madeiras cremosas formam uma assinatura refinada, moderna e adequada para praticamente qualquer ocasião.",
    "occasion": "Trabalho, encontros e eventos",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 24,
    "name": "Sauvage",
    "brand": "Dior",
    "inspired": "Sauvage — Dior",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/sauvage.webp",
    "official": "https://www.dior.com/pt_br/beauty/products/sauvage-eau-de-parfum",
    "notes": [
      "Bergamota",
      "Pimenta",
      "Ambroxan",
      "Madeiras"
    ],
    "short": "Fresco, aromático e marcante.",
    "description": "Bergamota luminosa e especiarias encontram uma base ambarada e mineral, resultando em uma fragrância moderna e expansiva.",
    "occasion": "Dia a dia, encontros e festas",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 25,
    "name": "Stallion Leather",
    "brand": "Carolina Herrera",
    "inspired": "Stallion Leather — Carolina Herrera",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/stallion-leather.webp",
    "official": "https://www.carolinaherrera.com/",
    "notes": [
      "Couro",
      "Violeta",
      "Cardamomo",
      "Madeiras"
    ],
    "short": "Couro elegante, escuro e sofisticado.",
    "description": "Uma interpretação luxuosa do couro, suavizada por notas florais e especiarias, com acabamento quente, polido e envolvente.",
    "occasion": "Noites e ocasiões formais",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 26,
    "name": "Black Orchid",
    "brand": "Tom Ford",
    "inspired": "Black Orchid — Tom Ford",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/black-orchid.webp",
    "official": "https://www.tomfordbeauty.com/product/black-orchid-eau-de-parfum",
    "notes": [
      "Trufa",
      "Orquídea",
      "Chocolate",
      "Patchouli"
    ],
    "short": "Floral oriental, escuro e opulento.",
    "description": "Uma composição intensa de flores exóticas, especiarias, chocolate e madeiras, criada para quem busca presença e personalidade.",
    "occasion": "Noites e festas",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 27,
    "name": "Carmina",
    "brand": "Creed",
    "inspired": "Carmina — Creed",
    "category": "feminino",
    "price": 65,
    "image": "assets/perfumes/carmina.webp",
    "official": "https://creedboutique.com/products/carmina",
    "notes": [
      "Cereja negra",
      "Rosa",
      "Violeta",
      "Âmbar"
    ],
    "short": "Floral frutado, sensual e elegante.",
    "description": "Cereja escura e pimenta rosa abrem caminho para rosa e violeta, sobre uma base ambarada, macia e sofisticada.",
    "occasion": "Encontros e eventos especiais",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 28,
    "name": "Oud Maracujá",
    "brand": "Maison Crivelli",
    "inspired": "Oud Maracujá — Maison Crivelli",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/oud-maracuj.webp",
    "official": "https://maisoncrivelli.com/products/oud-maracuja",
    "notes": [
      "Maracujá",
      "Oud",
      "Rosa",
      "Couro"
    ],
    "short": "Frutado exótico, amadeirado e intenso.",
    "description": "O contraste entre maracujá suculento e oud profundo cria uma fragrância ousada, moderna e inesquecível, com couro e rosa ao fundo.",
    "occasion": "Noites e ocasiões marcantes",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 29,
    "name": "Guidance",
    "brand": "Amouage",
    "inspired": "Guidance — Amouage",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/guidance.webp",
    "official": "https://amouage.com/products/guidance",
    "notes": [
      "Pera",
      "Avelã",
      "Rosa",
      "Sândalo"
    ],
    "short": "Floral frutado, cremoso e hipnótico.",
    "description": "Pera, avelã, açafrão e rosa se unem a madeiras cremosas e âmbar, formando uma fragrância rica, envolvente e original.",
    "occasion": "Encontros e eventos especiais",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 30,
    "name": "By the Fireplace",
    "brand": "Maison Margiela — Replica",
    "inspired": "By the Fireplace — Maison Margiela — Replica",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/by-the-fireplace.webp",
    "official": "https://www.maisonmargiela-fragrances.us/fragrances/replica/replica-by-the-fireplace.html",
    "notes": [
      "Castanha",
      "Baunilha",
      "Madeira queimada",
      "Bálsamo"
    ],
    "short": "Amadeirado gourmand, quente e acolhedor.",
    "description": "Evoca uma lareira acesa com madeira tostada, castanhas assadas e baunilha, criando uma sensação aconchegante e nostálgica.",
    "occasion": "Noites frias e momentos aconchegantes",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 31,
    "name": "Bvlgari Man Wood Essence",
    "brand": "Bvlgari",
    "inspired": "Bvlgari Man Wood Essence — Bvlgari",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/bvlgari-man-wood-essence.webp",
    "official": "https://www.bulgari.com/",
    "notes": [
      "Cítricos",
      "Cipreste",
      "Vetiver",
      "Cedro"
    ],
    "short": "Verde amadeirado, moderno e natural.",
    "description": "Cítricos e folhas verdes encontram cipreste, vetiver e cedro, criando uma fragrância urbana com forte conexão à natureza.",
    "occasion": "Trabalho e dia a dia",
    "season": "Primavera e outono",
    "performance": "Alta"
  },
  {
    "id": 32,
    "name": "Bvlgari Black",
    "brand": "Bvlgari",
    "inspired": "Bvlgari Black — Bvlgari",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/bvlgari-black.webp",
    "official": "https://www.bulgari.com/",
    "notes": [
      "Chá preto",
      "Borracha",
      "Couro",
      "Baunilha"
    ],
    "short": "Fumado, couro e baunilha, muito original.",
    "description": "Uma composição cult que mistura chá preto, borracha, couro e baunilha em um contraste urbano, quente e surpreendente.",
    "occasion": "Noites e ocasiões criativas",
    "season": "Outono e inverno",
    "performance": "Alta"
  },
  {
    "id": 33,
    "name": "Terre d'Hermès",
    "brand": "Hermès",
    "inspired": "Terre d'Hermès — Hermès",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/terre-d-herms.webp",
    "official": "https://www.hermes.com/us/en/product/terre-d-hermes-eau-de-toilette-V107188V0/",
    "notes": [
      "Laranja",
      "Pimenta",
      "Vetiver",
      "Cedro"
    ],
    "short": "Cítrico mineral, seco e elegante.",
    "description": "Laranja amarga, pimenta e vetiver se unem a madeiras e notas minerais, criando uma assinatura madura, sofisticada e inconfundível.",
    "occasion": "Trabalho e ocasiões formais",
    "season": "Todas as estações",
    "performance": "Alta"
  },
  {
    "id": 34,
    "name": "Vibrato",
    "brand": "Sospiro",
    "inspired": "Vibrato — Sospiro",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/vibrato.webp",
    "official": "https://sospirointernational.com/",
    "notes": [
      "Toranja",
      "Bergamota",
      "Gengibre",
      "Almíscar"
    ],
    "short": "Cítrico aromático, vibrante e luxuoso.",
    "description": "Cítricos brilhantes e gengibre encontram um coração aromático e uma base limpa de almíscar e madeiras, com efeito elegante e expansivo.",
    "occasion": "Trabalho, viagens e eventos",
    "season": "Primavera e verão",
    "performance": "Alta"
  },
  {
    "id": 35,
    "name": "Bleu L'Exclusif",
    "brand": "Chanel",
    "inspired": "Bleu L'Exclusif — Chanel",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/bleu-l-exclusif.webp",
    "official": "https://www.chanel.com/",
    "notes": [
      "Madeiras aromáticas",
      "Âmbar",
      "Couro",
      "Incenso"
    ],
    "short": "Amadeirado intenso, profundo e refinado.",
    "description": "Uma leitura mais densa e luxuosa do universo Bleu, com madeiras escuras, nuances ambaradas e uma presença elegante e noturna.",
    "occasion": "Noites e ocasiões formais",
    "season": "Outono e inverno",
    "performance": "Muito alta"
  },
  {
    "id": 36,
    "name": "Reflection 45",
    "brand": "Amouage",
    "inspired": "Reflection 45 — Amouage",
    "category": "masculino",
    "price": 65,
    "image": "assets/perfumes/reflection-45.webp",
    "official": "https://amouage.com/products/reflection-45-man",
    "notes": [
      "Lavanda",
      "Néroli",
      "Íris",
      "Sândalo"
    ],
    "short": "Cremoso, refinado e luxuoso.",
    "description": "Flores brancas, especiarias suaves e madeiras cremosas formam uma fragrância polida, complexa e extremamente elegante.",
    "occasion": "Eventos e ocasiões formais",
    "season": "Todas as estações",
    "performance": "Muito alta"
  },
  {
    "id": 37,
    "name": "Bal d'Afrique",
    "brand": "Byredo",
    "inspired": "Bal d'Afrique — Byredo",
    "category": "compartilhavel",
    "price": 65,
    "image": "assets/perfumes/bal-d-afrique.webp",
    "official": "https://www.byredo.com/us_en/p/bal-d-afrique-eau-de-parfum",
    "notes": [
      "Bergamota",
      "Néroli",
      "Violeta",
      "Vetiver"
    ],
    "short": "Cítrico floral, solar e artístico.",
    "description": "Uma fragrância luminosa e sofisticada, com cítricos, flores delicadas, vetiver e madeiras, equilibrando frescor e aconchego.",
    "occasion": "Dia a dia, viagens e encontros",
    "season": "Primavera e verão",
    "performance": "Alta"
  }
];
